server:
  ingress:
    enabled: true
    ingressClassName: external-nginx
    annotations:
      kubernetes.io/ingress.class: "external-nginx"
      alb.ingress.kubernetes.io/scheme: "internet-facing"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      ingress.kubernetes.io/force-ssl-redirect: "true"


    hosts:
      - argocd.cloudwitches.online

#     # paths:
#     #   - path: /
#     #     pathType: Prefix

    tls:
      - hosts:
          - argocd.cloudwitches.online
        secretName: argocd-tls
